name: app
description: " "
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.2
  flutter_rating_bar: ^4.0.0
  cloud_firestore: ^5.6.10
  firebase_core: ^3.15.0
  shared_preferences: ^2.2.2
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/fondo.png

  uses-material-design: true

